#!/bin/bash

# 检查输入参数
if [ $# -lt 1 ]; then
  echo "Usage: $0 <app_instance_label> [-n <namespace>] [kubectl logs options...]"
  exit 1
fi

# 设置默认值
namespace=""
logs_options=""
app_instance_label=""

# 解析命令行参数
while [ $# -gt 0 ]; do
  case "$1" in
    -n)
      shift
      if [ $# -gt 0 ]; then
        namespace="-n $1"
      else
        echo "Missing value for -n option."
        exit 1
      fi
      ;;
    *)
      if [ -z "$app_instance_label" ]; then
        app_instance_label=$1
      else
        logs_options+=" $1"
      fi
      ;;
  esac
  shift
done

# 使用 kubectl 获取符合条件的 Pod 名称，并指定命名空间（如果提供了）
pod_name=$(kubectl get pods -l app.kubernetes.io/instance=$app_instance_label $namespace -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

# 检查是否找到符合条件的 Pod
if [ -z "$pod_name" ]; then
  echo "No Pod found with label app.kubernetes.io/instance=$app_instance_label in namespace $namespace"
  exit 1
fi

# 使用 kubectl logs 获取 Pod 的日志，并附加额外的参数
kubectl logs $pod_name $namespace $logs_options
